In [1]:
# Import necessary PyTorch modules
import torch
import torch.nn as nn

# Define a custom neural network model by subclassing nn.Module
class Model(nn.Module):

    def __init__(self, num_features):
        super().__init__()  # Initialize the base class

        # Define the network architecture using nn.Sequential for cleaner code
        self.network = nn.Sequential(
            nn.Linear(num_features, 3),  # First layer: fully connected (input -> 3 neurons)
            nn.ReLU(),                   # Activation function: ReLU
            nn.Linear(3, 1),             # Second layer: 3 neurons -> 1 output
            nn.Sigmoid()                 # Sigmoid to output probability (for binary classification)
        )

    def forward(self, features):
        # Define the forward pass
        out = self.network(features)
        return out


In [2]:
# Create a random dataset with 10 samples and 5 features each
features = torch.rand(10, 5)

# Instantiate the model by passing the number of features (5 in this case)
model = Model(features.shape[1])

# Perform a forward pass through the model
# You can call model(features) directly instead of model.forward(features)
output = model(features)

# Print the output probabilities from the model
print(output)


tensor([[0.4172],
        [0.4658],
        [0.4505],
        [0.4635],
        [0.4295],
        [0.4580],
        [0.4620],
        [0.4579],
        [0.4591],
        [0.4425]], grad_fn=<SigmoidBackward0>)


In [4]:
# Access the second Linear layer (index 2 in Sequential)
print(model.network[2].weight)  # This is Linear(3, 1)


Parameter containing:
tensor([[-0.4492, -0.2522, -0.3899]], requires_grad=True)


In [6]:
import torch
import torch.nn as nn

class Model(nn.Module):
    def __init__(self, num_features):
        super().__init__()

        # Define layers with explicit names for easy access
        self.linear1 = nn.Linear(num_features, 3)
        self.relu = nn.ReLU()
        self.linear2 = nn.Linear(3, 1)
        self.sigmoid = nn.Sigmoid()

    def forward(self, features):
        x = self.linear1(features)
        x = self.relu(x)
        x = self.linear2(x)
        out = self.sigmoid(x)
        return out


In [7]:
# Create dummy input
features = torch.rand(10, 5)

# Create model
model = Model(features.shape[1])

# Forward pass
output = model(features)

# Access weights of second linear layer
print(model.linear2.weight)


Parameter containing:
tensor([[ 0.2100, -0.0299, -0.5493]], requires_grad=True)


In [8]:
!pip install torchinfo

In [10]:
from torchinfo import summary

# Summarize the model structure with an input shape of (10 samples, 5 features)
summary(model, input_size=(10, 5))


Layer (type:depth-idx)                   Output Shape              Param #
Model                                    [10, 1]                   --
├─Linear: 1-1                            [10, 3]                   18
├─ReLU: 1-2                              [10, 3]                   --
├─Linear: 1-3                            [10, 1]                   4
├─Sigmoid: 1-4                           [10, 1]                   --
Total params: 22
Trainable params: 22
Non-trainable params: 0
Total mult-adds (Units.MEGABYTES): 0.00
Input size (MB): 0.00
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.00